### ISSUE TITLE
Can't get autopilot wordpress to work.

### ISSUE THREAD

**Issue by khangngu** [autopilotpattern/wordpress#32]
I deployed autopilot/wordpress.  After all 7 instances were created, I noticed that WordPress app was not completely configured and thus not running on the wordpress_wordpress_1 instance.  I logged on to the consul UI (http://165.225.149.83:8500/ui/#/dc1/services/mysql) and noticed that the entry "mysql-primary" was not shown.  It looked like mysql instance became live but didn't mark itself as the primary in Consul.  I was able to manually login to the database on mysql.  I executed "docker logs wordpress_mysql_1", and saved  the snippet of the log here:  https://gist.github.com/khangngu/59a2af346bbb598d4a01cc0912d60d40.  Can someone please  help detect what went wrong with my deployment?
Thanks,
-khang-

**Comment by misterbisson** [comment]
@khangngu this is the last log output before an error:

> 2016/10/06 22:30:53 INFO manage snapshot completed, uploading to object store

Uploads to the object store require a `MANTA_BUCKET`, `MANTA_USER`, `MANTA_KEY_ID`, and `MANTA_PRIVATE_KEY`. Have you confirmed all of those look valid in your `_env` file? Does the `MANTA_BUCKET` already exist (backups fail if not)? Does the `MANTA_USER` have access? Do all the pieces tie up?

My `MANTA_BUCKET` value is:

```
MANTA_BUCKET=/joybisson/stor/triton-mysql
```

Right now it includes:

```
$ mls //joybisson/stor/triton-mysql
[...]
mysql-backup-2016-09-28T16-55-26Z
mysql-backup-2016-10-04T18-19-11Z
```

**Comment by khangngu** [comment]
I also suspected that it had to do something with the backup.

I did have the following settings in my _env file:

MANTA_BUCKET= /khangngu/stor/wpbackup
MANTA_USER= khangngu
MANTA_KEY_ID=c5:48:5a:7f:c0:9e:a5:b8:ef:a3:43:1b:fa:94:b9:61

as well as MANTA_PRIVATE_KEY

However, I noticed that there is no backup file under that bucket directory.

$ mls /khangngu/stor/wpbackup

returned nothing.

Thanks,
-khang-

**Comment by khangngu** [comment]
I found the culprit: my MANTA_PRIVATE_KEY was encrypted.  I decrypted my private key, reran setup.sh, reran docker-compose, and everything is working now.

-khang-
