### ISSUE TITLE
Specificity for Manta configuration

### ISSUE THREAD

**Issue by alexandrascript** [autopilotpattern/wordpress#39]
When first going through this setup, I was unsure of how to properly setup the Manta configuration. In the README file, it says:

```
MANTA_BUCKET= # an existing Manta bucket
MANTA_USER= # a user with access to that bucket
```

I think users would be better served with more specificity. Such as:

```
MANTA_BUCKET=/<username>/store/bucketname  # an existing Manta bucket
MANTA_USER=<username> # a user with access to that bucket
```

**Comment by misterbisson** [comment]
Open a PR with that change?

**Comment by alexandrascript** [comment]
Will do!

**Comment by alexandrascript** [comment]
PR opened: https://github.com/autopilotpattern/wordpress/pull/40

**Comment by misterbisson** [comment]
Fixed with https://github.com/autopilotpattern/wordpress/pull/40
